[package]
name = "ckb-std"
version = "0.7.4"
authors = ["Nervos network"]
edition = "2018"
license = "MIT"
repository = "https://github.com/nervosnetwork/ckb-std"
description = "This library contains serveral modules help you write CKB contract with Rust"
exclude = ["docs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["allocator", "ckb-types"]
allocator = [ "buddy-alloc" ]
simulator = [ "ckb-x64-simulator" ]

[build-dependencies]
cc = "1.0"

[dependencies]
ckb-types = { package = "ckb-standalone-types", git = "https://github.com/keroro520/ckb-standalone-types", tag = "v0.0.2", default-features = false, optional = true }
buddy-alloc = { version = "0.4.1", optional = true }
ckb-x64-simulator = { version = "0.4.0", optional = true }
